# Generated by Django 4.1.3 on 2023-03-02 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='puplit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puppit', to='employe.pulpit', verbose_name='Кафедра'),
        ),
    ]
